language: php
php:
    - 7.3
    - 7.4

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq postfix
    
before_script: 
    - sudo service postfix stop
    - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
    - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
    - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"
    
    - composer self-update
    - composer install --prefer-dist --no-progress --no-suggest
    
script: 
    - vendor/bin/phpunit --stderr
