language: php
php:
    - 7.2
    - 7.3

before_install:
    sudo apt-get update
    sudo apt-get install sendmail
    
before_script: 
    - composer self-update
    - composer update
    
script: 
    - vendor/bin/phpunit --stderr
